### ISSUE TITLE
API Key at ipinfodb is not provided to free email (gmail, yahoo etc.) 

### ISSUE THREAD

**Issue by saurabh-deochake** [tuxmascot/ip-location-map#3]
Hi,

I wanted to try your script and as said in Readme, the user needs to get API key from http://ipinfodb.com/. However, while registering, the said website does not allow people with free email services like gmail, yahoo etc. to receive API key. 

Therefore, I was wondering can we not use some other API which provides access key to everybody ?(even who have free email service?) I guess we can use Google API too. 

Thanks & regards,
Saurabh.

**Comment by tuxxy** [comment]
Seems it could be done with this: http://freegeoip.net
I'll work on a build for my fork and, if it works, I'll send a pull request.

It seems this one doesn't need an API key, but I haven't looked extensively at it. There may be a few restrictions.

For my fork, I plan on integrating it into one file that does a few other things. I also plan on integrating it into a web app for fun.

EDIT: This API allows you to have 10,000 queries an hour. The current one doesn't have that limitation, I think.

**Comment by tuxxy** [comment]
I went ahead and built it with the freegeoip API. You can find it here:
https://github.com/tuxmascot/ip-location-map/tree/freegeoip

If @joakimalgroy would like, he can make a branch that uses this API.

**Comment by saurabh-deochake** [comment]
Thank you @tuxmascot it works perfectly. 

Just a quick question to @joakimalgroy and @tuxmascot, how about using logging function to log the steps in a log file? I have started working on it. Please let me know your views on it.

**Comment by tuxxy** [comment]
There isn't really a need to log anything. Logging things to a file will
only kill performance.

Logging is only necessary in code bases that have lots of room for failure.
Here, it's pretty self-evident.

This reminds me, I should be catching exceptions in that code for
`urllib`...

**Comment by saurabh-deochake** [comment]
Yeah. That is also true, @tuxmascot. By the way, can we create one "enhancements" thread? We can discuss all enhancements to this script there.

**Comment by tuxxy** [comment]
I'm in the process of revamping the whole thing to work in a webapp on my site soon. If you start it, I'll contribute.

**Comment by saurabh-deochake** [comment]
Oh, I see. I will do it.
